version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: sa
    networks:
        - net_snomed
    volumes:
        - ./RF2Release:/RF2Release

  app:
    build: .
    command: runserver 0.0.0.0:8000
    entrypoint: python3 manage.py
    volumes:
        - ./src:/code
    expose:
        - "8000"
    ports:
        - "8000:8000"
    depends_on:
        - db
    #restart: always
    networks:
        - net_snomed

  generate:
    build: .
    command: bash -c 'mkdir src && django-admin startproject app src'
    volumes:
        - .:/code
    depends_on:
        - db
    networks:
        - net_snomed

  manage:
    build: .
    entrypoint: python3 manage.py
    volumes:
        - ./src:/code
    depends_on:
        - db
    networks:
        - net_snomed
networks:
    net_snomed: